spring:
  profiles: default
  datasource:
    url: jdbc:mysql://localhost:3306/contest?useUnicode=true&characterEncoding=utf8&autoReconnect=true
    username: root
    password: password
debug: true
mybatis:
  type-aliases-package: com.keji.contest.model
  config-location: classpath:mybatis.xml

---
spring:
  profiles: pro
  datasource:
    url: jdbc:mysql://localhost:3306/contest?useUnicode=true&characterEncoding=utf8&autoReconnect=true
    username: qa
    password: LuGlobalPass4!
mybatis:
  type-aliases-package: com.keji.contest.model
  config-location: classpath:mybatis.xml