spring:
  datasource:
    url: jdbc:mysql://localhost:3306/contest?useUnicode=true&characterEncoding=utf8&autoReconnect=true
    username: qa
    password: LuGlobalPass4!
mybatis:
  type-aliases-package: com.keji.contest.model
  config-location: classpath:mybatis.xml
